// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5puwGOPjkqEKAhems2iOxdZKTn6Rsrhw',
    appId: '1:631618245831:web:af67983c25e7139b7fdae2',
    messagingSenderId: '631618245831',
    projectId: 'avali-app-menudigital',
    authDomain: 'avali-app-menudigital.firebaseapp.com',
    databaseURL: 'https://avali-app-menudigital-default-rtdb.firebaseio.com',
    storageBucket: 'avali-app-menudigital.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK-DGFLcye6yvPMarq0RxB_oGx6n9Re3s',
    appId: '1:631618245831:android:6472b51c5a1c9a5c7fdae2',
    messagingSenderId: '631618245831',
    projectId: 'avali-app-menudigital',
    databaseURL: 'https://avali-app-menudigital-default-rtdb.firebaseio.com',
    storageBucket: 'avali-app-menudigital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSW36Vu1PYQdlt6dxupWxlqvOum84xoZ0',
    appId: '1:631618245831:ios:e7ed6d3a1a2e58777fdae2',
    messagingSenderId: '631618245831',
    projectId: 'avali-app-menudigital',
    databaseURL: 'https://avali-app-menudigital-default-rtdb.firebaseio.com',
    storageBucket: 'avali-app-menudigital.firebasestorage.app',
    androidClientId: '631618245831-nunrctjknnmodj806os6i7r3o928edlq.apps.googleusercontent.com',
    iosClientId: '631618245831-chectir3de2tiaa8fdfma9bj53hsh22m.apps.googleusercontent.com',
    iosBundleId: 'com.example.menuDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSW36Vu1PYQdlt6dxupWxlqvOum84xoZ0',
    appId: '1:631618245831:ios:e7ed6d3a1a2e58777fdae2',
    messagingSenderId: '631618245831',
    projectId: 'avali-app-menudigital',
    databaseURL: 'https://avali-app-menudigital-default-rtdb.firebaseio.com',
    storageBucket: 'avali-app-menudigital.firebasestorage.app',
    androidClientId: '631618245831-nunrctjknnmodj806os6i7r3o928edlq.apps.googleusercontent.com',
    iosClientId: '631618245831-chectir3de2tiaa8fdfma9bj53hsh22m.apps.googleusercontent.com',
    iosBundleId: 'com.example.menuDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5puwGOPjkqEKAhems2iOxdZKTn6Rsrhw',
    appId: '1:631618245831:web:6fbc959fdefad8f37fdae2',
    messagingSenderId: '631618245831',
    projectId: 'avali-app-menudigital',
    authDomain: 'avali-app-menudigital.firebaseapp.com',
    databaseURL: 'https://avali-app-menudigital-default-rtdb.firebaseio.com',
    storageBucket: 'avali-app-menudigital.firebasestorage.app',
  );
}
